# The URL the site will be built for
base_url = "https://bprog.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hyde"

title = "io.Think"
description = "”Programming isn’t about what you know; it’s about what you can figure out.” - Chris Pine"

[extra]
# Put all your custom variables here

hyde_sticky = true
hyde_links = [
    { url = "mailto:ostafi_ion@yahoo.com", name = "ostafi_ion@yahoo.com" },
]
