# The URL the site will be built for
base_url = "https://bprog.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "toucan"

title = "Engineering software"
description = "”Programming isn't about what you know; it's about what you can figure out.” - Chris Pine"
default_language = "en"

[extra]
title = "Software mushrooms"
title_pic = "/mushroom.png"
description = "Programming isn't about what you know; it's about what you can figure out."

